name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        

jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: https://orge67d055b.crm.dynamics.com/
      PRODUCTION_ENVIRONMENT_URL: https://org876fe060.crm.dynamics.com/
      CLIENT_ID: f52669b9-f10a-4d8b-a7eb-b5d44ac30b8e
      TENANT_ID: 148ced59-97d6-4805-bc47-1b511373f0dd      
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
